# Generated by Django 5.0 on 2023-12-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='phone',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
